name: Build and Test Java Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Compile Java Code
        run: javac -d bin src/main/java/com/ListaTareas/control/*.java
        working-directory: ${{ github.workspace }}

      - name: Run Tests
        run: java -cp bin:src/test Main
        working-directory: ${{ github.workspace }}
